### ISSUE TITLE
CTRL + K doesn't work on Vivaldi

### ISSUE THREAD

**Issue by haroldao** [alyssaxuu/omni#1]

**Comment by alyssaxuu** [comment]
Sadly this appears to be a problem with Vivaldi, for all extensions with shortcuts. They [do not seem to support it at the moment](https://forum.vivaldi.net/topic/31027/keyboard-shortcuts-not-working-with-extensions). [This is the only way you could fix it](https://forum.vivaldi.net/topic/31027/keyboard-shortcuts-not-working-with-extensions/23?_=1641913385463&lang=en-US) from your end from what I've read.

**Comment by haroldao** [comment]
okay ty :)
