### ISSUE TITLE
Feature Request: Custom inputs for Commands 

### ISSUE THREAD

**Issue by mrwildenfree** [alyssaxuu/omni#106]
First off, thank you for creating this! Already see how helpful this will be.

I would to request a feature that would allow us to customize what the commands that we input are, for instance, I would like to be able to change the configurations like so:

- /action —→ "/a "
- /remove —→ "/x "
- /bookmarks —→ "/b "
- /history —→ "/h "
- /tabs —→ "/t "

Where the space at the end would be the confirmation of the action / command meant to activate. Similar to something like Alfred & how you can customize those Workflow prompts.

Thanks for the consideration & thank you again for the awesome tool!

**Comment by mrwildenfree** [comment]
I might have been too quick to jump, as after testing it out I do believe the auto-complete feature that currently exists does a sufficient enough job of fulfilling this request. 

While it's not exactly a custom key input for the Commands, it is more than enough for what the current starting letter options are.

**Comment by rilaby** [comment]
It's true - autocomplete works, but it's not something that's easy to figure out on the first try. @alyssaxuu great product - thanks for the effort you've put in!
