### ISSUE TITLE
[suggestion] - Open in new tab

### ISSUE THREAD

**Issue by remotealex** [alyssaxuu/omni#13]
Love the extension! I've been using alfred app for age and this is a perfect browser companion.

I often open Omni while looking at a tab I want to keep open. It would be nice to be able to hold ctrl or cmd and press rtn to open in a new tab :)

**Comment by alyssaxuu** [comment]
Ah I was debating this - originally it did indeed open in a new tab by default, but I felt that sort of slowed me down. But having it as an option would definitely be good. Holding a key could be the solution, working for both click + return. Will look into implementing this! Not sure though if it might be a bit hidden, can't really think how I could tell the user they can do this in context, hmm.

**Comment by remotealex** [comment]
Nice! My instinct was to hold `cmd` on mac, this would change the label on the right to indicate it was going to open in a new tab. I hope that makes sense :)

**Comment by alyssaxuu** [comment]
Yeah I suppose it would be the same as when attempting to open a link in a new tab, that makes sense.

**Comment by alyssaxuu** [comment]
Done, should be working now.
