### ISSUE TITLE
[Suggestion] option for display url address

### ISSUE THREAD

**Issue by liuyx7894** [alyssaxuu/omni#17]
for example:
<img width="743" alt="WX20220114-182821@2x" src="https://user-images.githubusercontent.com/3355327/149501030-04aa4b1e-536d-4b62-88e1-fe707fbacc3b.png">

it's very hard to recognize URL only through the title

**Comment by alyssaxuu** [comment]
True. Maybe replacing "browsing history" with the URL? Unsure if it would be clear by the icon alone.

**Comment by liuyx7894** [comment]
> True. Maybe replacing "browsing history" with the URL? Unsure if it would be clear by the icon alone.

In my opinion,` /history` is very clear for showing which its the source.

Replacing `Browsing history` with the URL is a nice option, or maybe you could add one more line for displaying the URL.

**Comment by alyssaxuu** [comment]
Done, I also added this for bookmarks since some were also similar, and they can be distinguished by the star anyway.
