### ISSUE TITLE
Website CSS can interfere with Omni's styles

### ISSUE THREAD

**Issue by PullJosh** [alyssaxuu/omni#2]
[Scratch](https://scratch.mit.edu/) has styles which apply to `#footer`, and they make the footer in Omni look wrong. To reduce the chance of collisions, it might be helpful to use names like `#omni-footer` and so on.

P.S. I absolutely love this extension! Such a cool idea, and really well executed. 😄

**Comment by alyssaxuu** [comment]
I just updated the selectors. I should have probably used an iframe, would have been easier in retrospect. Hopefully the changes will be live in the Chrome Store soon :) And thank you!

**Comment by PullJosh** [comment]
Wow! You are *quick*.
