### ISSUE TITLE
Shortcut not working in new tab.

### ISSUE THREAD

**Issue by Archonz-crazy** [alyssaxuu/omni#21]
Situation: Pressing Ctrl+K on a new tab page.
Expected output: the menu should pop with all the info
Actual output: there is not activity in the new tab.

device: HP laptop, Windows 11, chrome latest update.

**Comment by alyssaxuu** [comment]
It's not possible to inject code in the new tab page unfortunately (a limitation of Chrome Extensions). I can't even show an alert or a warning, so there's nothing I can do :( Sorry

**Comment by Archonz-crazy** [comment]
Oh...didn't know about this. Still, a great tool, ma'am. Thanks for the fast handling.

**Comment by alyssaxuu** [comment]
I've one a workaround so it should work in new tab now.

**Comment by Archonz-crazy** [comment]
Wow....thanks!!!!!
