### ISSUE TITLE
Open direct URLs

### ISSUE THREAD

**Issue by edgarasben** [alyssaxuu/omni#25]
Could be a quick but very useful feature - simply if I can type url and open a website from the search. e.g. by typing: "alyssax.com". 

Awesome product, congrats with the launch! ;)

**Comment by alyssaxuu** [comment]
That's interesting, although unsure how that could work. Maybe if there's a TLD in the search input (.com, .net, .org...) it could add a result in the #1 position that lets you go to that URL, while keeping all matching entries for bookmarks and tabs underneath?

**Comment by alyssaxuu** [comment]
Added it in. I also added an action to search, thought it might be useful.
