### ISSUE TITLE
Error in Background.js

### ISSUE THREAD

**Issue by aarshcode** [alyssaxuu/omni#27]
Hay!

Whenever I try to load the extension, I get an error saying.

![Screenshot 2022-01-15 at 9 55 30 AM](https://user-images.githubusercontent.com/82889744/149608761-a35b88eb-77d0-430c-8d70-aa69a1439566.png)

**Comment by alyssaxuu** [comment]
Yeah, the error is caused because the extension is attempting to inject itself in a chrome:// URL, when it is not possible. Doesn't really affect the functionality of the tool, but I could get rid of it by checking the URL before injecting.

**Comment by alyssaxuu** [comment]
Removed the error.
