### ISSUE TITLE
[Suggestion] Safari Extension

### ISSUE THREAD

**Issue by AurevoirXavier** [alyssaxuu/omni#29]
Awesome extension.
I'd love to pay for it if it can be listed on AppStore.

**Comment by alyssaxuu** [comment]
I've been looking into it, trying to convert it. The issue is that it appears many of the APIs that Omni currently uses aren't available for Safari, so it might have to be a very limited version of it. Also would basically need a complete overhaul.

**Comment by JulyFinal** [comment]
> I've been looking into it, trying to convert it. The issue is that it appears many of the APIs that Omni currently uses aren't available for Safari, so it might have to be a very limited version of it. Also would basically need a complete overhaul.

Even so, I'm looking forward to it! This is a great extension.
