### ISSUE TITLE
[Suggestion] Change default short

### ISSUE THREAD

**Issue by danielcaldas** [alyssaxuu/omni#30]
I'm using this and loving it so far ❤️ . One thing that is conflicting with my workflow. The default shortcut to open omni is `Command+K`. Don't take me wrong, this is configurable through the `chrome://extensions/shortcuts` panel, but I think the right default shortcut would be `Shift+Command+K`, for the following reasons:

* And many text editors (e.g. Github text fields) `Command+K` is the default shortcut to add links to selected text in markdown
* In Slack `Command+K` is the most used shortcut to navigate DMs
* maybe others?

Anyways, since I'm foreseeing quote a lot of users running into the above I would suggest the suggested default key to change to 

```json
"commands": {
	"open-omni": {
		"suggested_key": {
			"default": "Ctrl+Shift+K",
			"mac": "Command+Shift+K"
		},
		"description": "Open command menu"
	}
},
```

**Comment by alyssaxuu** [comment]
I'm open to changing it, if users don't mind. The only thing is I'm not sure what will happen with existing users, I wonder if it will stay the same for them. Otherwise it would be a big problem as Command+K wouldn't work anymore. So yeah hmm...

**Comment by danielcaldas** [comment]
> Otherwise it would be a big problem as Command+K wouldn't work anymore

True, anyways you're already mentioning this in the README.md, so it shouldn't be too hard to find it.

> ou can change the shortcut by going to chrome://extensions/shortcuts

**Comment by alyssaxuu** [comment]
I could maybe make it super prominent after you install the extension somehow, like "are you ok using command+k or do you want to change this?". But there's plenty of users who just automatically close the page anyway, so might not be that effective.

**Comment by danielcaldas** [comment]
> But there's plenty of users who just automatically close the page anyway, so might not be that effective.

Maybe keep monitoring, if you see users are looking a lot at this issue, that will give you the hint that something should be done about it.

Thanks for the extension btw, great work.

**Comment by edgarasben** [comment]
True. Many websites including [Tailwind CSS](https://tailwindcss.com/) or [Vercel Dashboard](https://vercel.com/dashboard) have the same quick search shortcut (`Command+K`). This plugin would prevent accessing the common website functionality.

One idea could be to display a text saying that users would have to press `Command+K` again to jump to the website's provided quick search bar. But actually I find it annoying, e.g. when [Stripe documentation](https://stripe.com/docs/api) overrides the default `Command+F` page search shortcut:
![image](https://user-images.githubusercontent.com/725324/149643289-2d29a038-db2d-42da-bc90-6f9e3bd50096.png)

On the other hand, this could be a good in-between solution that others might like (and Stripe decided to do it, so maybe it's not that bad)

**Comment by alyssaxuu** [comment]
Just changed it to Cmd/Ctrl+Shift+K. I've looked it up and it shouldn't change the shortcut for users who already have the extension installed, so should be fine.

**Comment by edgarasben** [comment]
Thank you for the update. Sorry to raise this again, but what should user do if they have another extension (e.g. Notion Web Clipper) using the same "Cmd/Ctrl+Shift+K" shortcut, but wanting to access Omni? Could they maybe customize the shortcut?

Otherwise the only option is to disable, in this case Notion Web Clipper.

**Comment by edgarasben** [comment]
I was not aware! Thanks!
