### ISSUE TITLE
[Bug] Multi-instances tab switching

### ISSUE THREAD

**Issue by dadyarri** [alyssaxuu/omni#32]
If opened multiple instances of Chrome, tab switching to tab in inactive window switches to tab with the same number as selected, but in current window.
OS: Windows 10;
Browser: Brave;

Don't know if it's fixable, let me know please

**Comment by alyssaxuu** [comment]
It is fixed but it hasn't gone live just yet. Will be a few minutes, up to an hour, version 1.2.9.
