### ISSUE TITLE
Will it work with Linux?

### ISSUE THREAD

**Issue by peterteszary** [alyssaxuu/omni#38]

**Comment by alyssaxuu** [comment]
I'm not sure? I think so, but I can't test it as I don't have Linux myself. if you have Linux yourself you could just follow the steps in the README and see if it works, I suppose, or through the Chrome Store directly.

**Comment by peterteszary** [comment]
Thank you for the reply! I have tried, but it just has not worked. Even if I changed the shortcuts, I couldn't get them to work.

**Comment by alyssaxuu** [comment]
Ah I see! And you've tried the most recent version? What browser are you using?
