### ISSUE TITLE
The ↑ arrow not correctly working

### ISSUE THREAD

**Issue by shincling** [alyssaxuu/omni#4]
Thanks for this tool.
I just began to test some of the features.
I found the up arrow not working ( the down arrow is ok).
To be detailed, the up-arrow will only work once to select two items, as follows:
![image](https://user-images.githubusercontent.com/14304866/149125371-620979a4-3011-44f5-8e7f-3427b5d40044.png)

My environment is Win10. 
Please check it. 

And, I found this tool reacts really snow in my side, wondering some problem here in Windows?

**Comment by alyssaxuu** [comment]
Yeah I fixed all those issues. It was due to an update I did for #2, unfortunately I missed a few selectors and it sort of messed everything up :(

**Comment by shincling** [comment]
Thanks and take it easy. Will wait the new version :)

**Comment by alyssaxuu** [comment]
Should be live now!
