### ISSUE TITLE
Add custom commands

### ISSUE THREAD

**Issue by aekanshd** [alyssaxuu/omni#43]
Hey, how can we add custom commands? For example, I need an action shortcut to open Google Calendar. I self-hosted the extension and also changed the hotkey to CMD+Shift+K but I get a few extension errors.

![IMG_20220116_155149.jpg](https://user-images.githubusercontent.com/30038178/149655998-a7d0d60f-ddd8-4f4f-a217-b5510e81fba0.jpg)

**Comment by alyssaxuu** [comment]
Hmm, you mean customize the commands for existing actions? There's certainly a lot of functionality that could be added, including being able to create your own actions.

And I see - is that preventing you from opening Omni?

**Comment by aekanshd** [comment]
Yup, I added a new line:

```
...
 
 ​                        ​{​title​:​"Open Google Calendar"​,​ ​desc​:​"View your events on Google Calendar"​,​ ​type​:​"action"​,​ ​action​:​"url"​,​ ​url​:​"https://calendar.google.com/"​,​ ​emoji​:​false​,​ ​favIconUrl​:​chrome​.​runtime​.​getURL​(​"assets/logo-calendar.png"​)​,​ ​keycheck​:​false​}​,
...
```

But somehow the extension crashes after the first use and the page gets killed.

**Comment by alyssaxuu** [comment]
I pasted your line in the array and it didn't work, but when I copy pasted an existing action and modified it myself it worked fine. Apparently there's some sort of invalid character in your code, but I could not find any?

**Comment by alyssaxuu** [comment]
Should be working fine, try writing it again from zero / copying an existing action and modifying the parameters.
