### ISSUE TITLE
"omni-extension" div causes rendering issues on some sites

### ISSUE THREAD

**Issue by ThatOtherAndrew** [alyssaxuu/omni#44]
### How the page looks: 
![image](https://user-images.githubusercontent.com/26030336/149657282-dda0e9f7-0888-4c51-b9f2-b5100bc2b4e5.png)
### How the page should look:
![image](https://user-images.githubusercontent.com/26030336/149657328-9090cc23-fc9f-444d-8777-86de97603348.png)

**Comment by alyssaxuu** [comment]
Fixed!
