### ISSUE TITLE
[suggestion] Add print as a command

### ISSUE THREAD

**Issue by gsabater** [alyssaxuu/omni#47]
Hello,

Loving the extension so far, but as I am very bad remembering things, i have set the shortcut to open omni as CTRL+P (just as in VSCODE).

This shortcut is used to print a page, which I rarely do, and chrome hasn't given me any problems assigning the shortcut.
The thing is that I think that having the option to do CTRL+P and search "print" to print a page would be something awesome to have.

Thanks for the work

**Comment by alyssaxuu** [comment]
That's a great idea, I've added it as an action with the shortcut in the latest version :)
