### ISSUE TITLE
Global scrollbar stylesheet in content.css breaks page's layout 

### ISSUE THREAD

**Issue by imyelo** [alyssaxuu/omni#48]
Before:
![image](https://user-images.githubusercontent.com/2399123/149750527-468c4a7b-a32e-4313-99c6-e1cc1743b966.png)

After:
![image](https://user-images.githubusercontent.com/2399123/149750385-d2b30cff-9ff1-47f3-ab0e-3e66272b6b7b.png)

https://github.com/alyssaxuu/omni/blob/master/src/content.css#L5

**Comment by alyssaxuu** [comment]
Will be fixed in the latest update!
