### ISSUE TITLE
[BUG] Autofocus and omnibox not working on Atlassian Jira

### ISSUE THREAD

**Issue by gsabater** [alyssaxuu/omni#49]
Looks like when im in jira I can open the omnibox normally with the shortcut, but the input has no focus at all.
Clicking the input has no effect, and I can't write at all on that page.

Clicking items work as expected, so i can change tabs, the problem is just on the input field

**Comment by alyssaxuu** [comment]
Hmm, I've just tried to use Jira with Omni and it seems to work fine - any specific page you're trying to use it in?

**Comment by gsabater** [comment]
You are right, it's not on every page.
The problem is specifically on a kanban project while the task card is open. I can't give you more detailed screenshots than this for privacy, sorry

![image](https://user-images.githubusercontent.com/4948172/149780888-976891d4-612d-428c-97c4-fe91fb412141.png)

**Comment by gsabater** [comment]
Opening the omnibox manually with the extension icon has the same behaviour, I guess its not something related to the keybind used to open it

**Comment by 036** [comment]
Can confirm I'm seeing the same behaviour. It also stops the search functionality working.

**Comment by alyssaxuu** [comment]
Hmm I can't find a way to fix this. I've tried a million different things, it seems to be a javascript thing (no CSS appears to be conflicting with the input), but I've listened to possible blur / focusout events and there were none. I just got the focus event on the input and that was it. 

Would appreciate any ideas - otherwise I might look into putting the whole omnibox inside an iframe to prevent it from conflicting with any page.

**Comment by gsabater** [comment]
Whelp, i tried a few things. You are completelly right that this isn't a css thing. I tried to focus the input both with jquery and vanilla js and the event is obliterated by some external JS.

I thought that maybe replacing the element after the dom is loaded and the page is renderer with something simple but effective like `element.outerHTML = element.outerHTML;` might clean all DOM events, but for some reason is not working either.

The only reference to any call that could prevent the focus from happening is this
![image](https://user-images.githubusercontent.com/4948172/149803153-5526af03-0cfd-47e9-ab0e-aea1b8f61090.png)

**Comment by yoroshikun** [comment]
Hint to a solution is that jira uses this specifically
https://github.com/theKashey/focus-lock/
Which is causing issues with focus scope

**Comment by alyssaxuu** [comment]
Ended up doing a bit of a focus fight - I installed the library and I managed to keep the focus on Omni. Should be working fine in the latest version!
