### ISSUE TITLE
Some favicons are missing

### ISSUE THREAD

**Issue by edgarasben** [alyssaxuu/omni#50]
Mabe a default favicon is needed in these cases:
![image](https://user-images.githubusercontent.com/725324/149788638-ad005eee-b11b-422a-a5ad-57890f688f02.png)

**Comment by alyssaxuu** [comment]
I am aware of the issue. I have set onerror + onload (to check if the image has dimensions, as a fallback to onerror) events to the images, but they don't always seem to trigger annoyingly. Not sure why :(

**Comment by edgarasben** [comment]
Maybe the event has to "await" for the images to fetch first? Just a super random guess, didn't look into code.

**Comment by alyssaxuu** [comment]
Managed to fix it.
