### ISSUE TITLE
Messes up js smooth scrolling

### ISSUE THREAD

**Issue by edgarasben** [alyssaxuu/omni#51]
When I enable the Omni extension, seems like it messes up the smooth scroll bezier curves on all websites.

For example, on https://webflow.com/pricing#account if you click on any of pricing plans, the scrolling is weird and bouncy. Same on any other site that uses js-based smooth scrolling.

**Comment by alyssaxuu** [comment]
Fixed in the latest version.

**Comment by edgarasben** [comment]
Thanks! Your speeds are incredible 😅
