### ISSUE TITLE
Provide UI feedback after executing actions from search bar

### ISSUE THREAD

**Issue by FranciscoPontes** [alyssaxuu/omni#52]
From the search bar menu, if I choose "Clear local storage", for example, there is no feedback if the operation was successful or not. Hence, I suggest adding something like a snackbar to inform the user of the output.

**Comment by alyssaxuu** [comment]
Added a toast for UI feedback in the latest version.

**Comment by FranciscoPontes** [comment]
Is this working? I've re-installed the chrome extension and see no toast

**Comment by alyssaxuu** [comment]
It's still currently "Pending review", can take up to an hour unfortunately.
