### ISSUE TITLE
[Suggestion] Add support for browser extensions to be launched via omni commands

### ISSUE THREAD

**Issue by batashahh** [alyssaxuu/omni#66]
This is a great extension and my use for it will increase immensely if the search also includes installed extensions. I have way too many chrome extensions I use everyday and pinning them all near the address bar makes it look cluttered while searching for the one I want to launch from the extensions menu (list) takes too much time. 
It would be immensely convenient if I could just type "Cookie Editor" or "Teleparty" on the omni search bar and press enter which then does the same thing that would usually take me at least 10 seconds or cost me a cluttered address bar.

**Comment by sahil-shubham** [comment]
Opening extension popups programatically isn't possible - https://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascript

**Comment by batashahh** [comment]
Oh no! That's too bad. Thanks for the information though!

**Comment by alyssaxuu** [comment]
Yeah it would be great if it was possible ^^
