### ISSUE TITLE
[bug] omni causes JIRA comments to only want to appear in a new page

### ISSUE THREAD

**Issue by jacobbednarz** [alyssaxuu/omni#68]
While using JIRA (I know, I know) clicking on "add comment" to an existing issue causes the comment box to open the comment model in the full page instead of opening in place below the existing content; kind of like the old school frame busting hacks.

To reproduce:

- Install v1.4.3 for Firefox on Mac
- Navigate to a JIRA issue
- Click "add comment" 
- Watch the frame busting like behaviour open the comment area in the whole page instead of auto-expand in place

I tried to grab some logs for this, but it looks like JIRA is super noisy with its own frontend logs, so it's pretty hard to decipher what (if anything) is coming from the extension. If you have a debug version lying around, I'm happy to load that into Firefox and provide some more debugging output.

**Comment by alyssaxuu** [comment]
So there is an old issue specifically related to this, #49, basically Jira was "focus fighting" and preventing Omni from being focused, so I had to add a library to combat this.

That said, I've just tried to follow all your steps and I couldn't reproduce, also v1.4.3 for Firefox on Mac. The comment auto-expands in place for me. Although I do notice at times with the comment input focused the Omni input gets frozen, so it appears the focus fight isn't always successful. Hmm.....

**Comment by jacobbednarz** [comment]
I've gone through a few versions, and it looks like this is only present in the bleeding edge versions (developer + aurora channels). Stable Firefox seems fine so let's close this out until it impacts stable as there is most likely something else at play here which may be addressed in Firefox itseld. Thanks for looking anyway!

**Comment by jraxxo** [comment]
unfortunately, i am facing the same issue - not using any bleeding edge version of FF, just plain ol' stable channel (I'm at 102.0.1 rn). 
it's annoying to the point where i decided to use a dedicated browser just for jira/confluence stuff (somewhat automated with choosy), but it's still breaking my workflow from time to time :/ 
any news on this?
