### ISSUE TITLE
fix: namespace injected theme CSS custom properties

### ISSUE THREAD

**Issue by darrylnoakes** [alyssaxuu/omni#82]
Currently, properties for the theming of the in-page interface are injected into the page without any namespacing of any kind.
E.g. `:root { --background: #000; }`.
This breaks pretty much anything that uses the same names.
It's fine for a site to have them un-namespaced, but an exte Sion injecting them shouldn't interfere with a page.

Please namespace them using an id/class or prefix them.
E.g. `#omni-extension-root { --background: #000; }` or `:root { --omni-background: #000; }`.
The prefix would work, but there would still be potential for naming collisions. Prefer the id/class namespacing if possible.

I currently can't use Omni because of this issue. If you resolve it, I will continue using Omni. Thanks!

**Comment by alyssaxuu** [comment]
Fixed!
